# This is a basic workflow to help you get started with Actions

name: Build and push the latest build to staging1

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

    runs-on: ubuntu-latest

      - uses: actions/checkout@v2
- name: Build and push staging image1
  # You may pin to the exact commit or the version.
  # uses: docker/build-push-action@0db984c1826869dcd0740ff26ff75ff543238fd9
  uses: docker/build-push-action@v1.1.1
  with:
   username: ContosoContainerRegistry17072
          password: g1Ef=LP4GX0Iiuc2vSpTsWK4CTBoOYn3
          registry: contosocontainerregistry17072.azurecr.io
          repository: contoso-website
          tags: latest
