name: Build and push the latest build to staging

on:
  push:
    branches: [ main ]

jobs:
  build_push_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: azure/docker-login@v1
        with:
          username: ContosoContainerRegistry17072
          password: g1Ef=LP4GX0Iiuc2vSpTsWK4CTBoOYn3
          login-server: contosocontainerregistry17072.azurecr.io
          
      - run: |
         docker build . -t contosocontainerregistry17072.azurecr.io/contoso-site:${{ github.sha }}
         docker push contosocontainerregistry17072.azurecr.io/contoso-site:${{ github.sha }}
