name: Build and push the latest build to staging

on:
  push:
    branches: [ main ]

jobs:
  build_push_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push staging image
        uses: docker/build-push-action@v1.1.1
        with:
          username: ContosoContainerRegistry17072
          password: g1Ef=LP4GX0Iiuc2vSpTsWK4CTBoOYn3
          registry: contosocontainerregistry17072.azurecr.io
          repository: contoso-website
          tags: latest
